### ISSUE TITLE
Enhance the development environment tutorial

### ISSUE THREAD

**Issue by hotloo** [suragch/Chimee#1]
This may be partially my issue, but IMHO, It seems to me that the complexity of just setting up the development environment for the project is quite a lot. 

It would be nice to have a quick setup guide for the project, which at least states
1. project dependencies
2. required external libraries
3. other pre-requisites. 

Another thing is that, the project seems to be broken on IntelliJ. The graphic preview is not loading correctly. Is there any setting or configuration that I need to do to get it right?

The screenshot is this:
![screenshot 2015-03-08 11 47 18](https://cloud.githubusercontent.com/assets/1831408/6545318/bb15b15c-c589-11e4-8708-f1ff34e0168a.png)

Keep up with the good work!

**Comment by hotloo** [comment]
This is my environment:

Mac OS X Yosemite
JDK 1.7
Android SDK API 21: Android 5.0 : com.android.support:support-v4:21.0.3

Gradle is configured by IntelliJ. 

There must be something wrong that I am not seeing.

**Comment by suragch** [comment]
Thanks for your suggestions. For now I will just try to answer your questions and at some future date I will make a supplemental document explaining more about setting up the development environment.

There shouldn't be any external libraries that need to be imported besides the basic Android support library that you listed. The custom fonts need to be in the assets/fonts folder but they are included in the github repository already and should be in the correct location when you do an import.

I am using the following setup on my machine:

Ubuntu 12.04
JDK 1.7
Android SDK API 21: Android 5.0 : com.android.support:support-v4:21.0.3
Android Studio

The graphics preview doesn't work because the layouts use MongolTextView.java, a custom subclass of TextView, which rotates and mirrors the text and also uses the custom fonts. That's why you get the error message about the Typeface.

Are you about to run the app in the debugger or on a device?

**Comment by suragch** [comment]
Thanks for your suggestions. For now I will just try to answer your 
questions and at some future date I will make a supplemental document 
explaining more about setting up the development environment.

There shouldn't be any external libraries that need to be imported 
besides the basic Android support library that you listed. The custom 
fonts need to be in the assets/fonts folder but they are included in the 
github repository already and should be in the correct location when you 
do an import.

I am using the following setup on my machine:

Ubuntu 12.04
JDK 1.7
Android SDK API 21: Android 5.0 : com.android.support:support-v4:21.0.3
Android Studio

The graphics preview doesn't work because the layouts use 
MongolTextView.java, a custom subclass of TextView, which rotates and 
mirrors the text and also uses the custom fonts. That's why you get the 
error message about the Typeface.

Are you about to run the app in the debugger or on a device?

**Comment by suragch** [comment]
Chimee now uses [mongol-library](https://github.com/suragch/mongol-library)

**Comment by suragch** [comment]
Since this is such an old issue, I'm closing it for now. Feel free to open a new one.

Currently I'm only releasing bug fixes for Chimee and not adding new features. Someday I may try to make a Flutter version but I'm no longer doing native Android development in Java.
